[package]
name = "geth-utils"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"


[dependencies]
ethers-core = "=2.0.0"
serde_json = "1.0.66"
hex = "0.4.3"

[build-dependencies]
gobuild = "0.1.0-alpha.1"
log = "0.4.14"
env_logger = "0.9"
