name: Weekly Circuits Benchmark

on:
  workflow_dispatch:
    inputs:
      BRANCH_NAME:
        description: 'BRANCH_NAME'
        required: true
  schedule:
    - cron: "0 0 * * MON"

env:
  BENCH_RESULTS_PASS: ${{ secrets.BENCH_RESULTS_PASS }}

jobs:
  taiko-weekly-circuits-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup
        run: |
          cd .github/weeklyBenchScripts
          ./github-action-setup.sh
        env:
          GITHUB_RUN_ID: ${{ vars.GITHUB_RUN_ID }}

      - name: Trigger
        run: |
          cd .github/weeklyBenchScripts
          ./github-action-trigger.sh
        env:
          GITHUB_RUN_ID: ${{ vars.GITHUB_RUN_ID }}
          BRANCH_NAME: ${{ inputs.BRANCH_NAME || github.event.client_payload.BRANCH_NAME || 'main' }}

      - name: Cleanup
        run: |
          cd .github/weeklyBenchScripts
          ./github-action-cleanup.sh
        if: always()
        env:
          GITHUB_RUN_ID: ${{ vars.GITHUB_RUN_ID }}
